### ISSUE TITLE
metavalue is set to the wrong value in the change event

### ISSUE THREAD

**Issue by FelixVicis** [robertdevore/delivery-drivers-for-woocommerce#10]
The change handler for driver availability will incorrectly update on some versions of jQuery. It always reports the metavalue as checked or not regardless of the value of the checkbox.

https://github.com/deviodigital/delivery-drivers-for-woocommerce/blob/cd40bf44633a3a3b43dcdad04a8df136c4c568b4/public/js/ddwc-public.js#L51

This line should actually be
```js
var metavalue = $(this).is(":checked") ? "checked" : "";
```

or even
```js
var metavalue = e.target.checked ? "checked" : "";
```

**Comment by robertdevore** [comment]
Thanks @FelixVicis this has been fixed in DDWC v3.0 👍
