### ISSUE TITLE
ddwc_driver_bulk_edit bug

### ISSUE THREAD

**Issue by Carve** [robertdevore/delivery-drivers-for-woocommerce#2]
Forwarded from support:

"they made error in last version , they removes ALL actions if you don;'t have role "driver".

https://plugins.trac.wordpress.org/changeset/2168577/delivery-drivers-for-woocommerce 
look for "function ddwc_driver_bulk_edit"
Please, report this bug to them..

you can fix it yourself, just move  code "return $actions;"    one line below
thanks, Alex"

**Comment by robertdevore** [comment]
@Carve Thanks for the heads up, I'll be pushing out an update later today :+1:
