### ISSUE TITLE
Delivery Address Unit Address Line 2 does not display on order

### ISSUE THREAD

**Issue by lopezdp** [robertdevore/delivery-drivers-for-woocommerce#6]
When an order is made, and when Google maps is integrated, the driver cannot see the Address Line 2 Data in the claimed order.

The order where google maps is integrated should have the shipping address available so the driver knows where to make the exact delivery.

This is in production and drivers have no idea where they are going. Ill fork the project but im sure you can figure this out faster.... hopefully? Thanks!!!

**Comment by freebs65** [comment]
this can be fixed in ddwc-pro-dashboard-shortcode.php
I added shipping instead of billing..
then here is the line.

echo '<td>'.$order_shipping_address_1. ', '.$order_shipping_address_2.', '. $order_shipping_city . ' ' . $order_shipping_state . ', ' . $order_shipping_postcode . '</td>';

**Comment by robertdevore** [comment]
This has been updated to use the built in WooCommerce formatted address `$order->get_formatted_shipping_address()` so I'm going to close this issue out.
